web:
  image: lunohq/relax
  environment:
    - RELAX_MUTEX_KEY=relax_mutex_key
    - RELAX_BOTS_KEY=relax_bots_key
    - RELAX_BOTS_PUBSUB=relax_bots_pubsub
    - RELAX_EVENTS_QUEUE=relax_events_queue
    - REDIS_URL=redis://redis:6379/3
  external_links:
    - services_redis_1:redis
